# docker compose -f docker-compose.yml -p development up --build

services:
  shop-db: 
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  keycloak:
    build:
      context: ./keycloak
      dockerfile: ./Dockerfile
    command: -v start-dev --import-realm
    volumes:
      - ./keycloak/imports/Shop_import.Development.json:/opt/keycloak/data/import/Shop_import.json
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - KC_HOSTNAME=http://localhost:8001/
      - KC_PROXY_HEADERS=xforwarded
    ports:
      - 8001:8080
    
  inventory-db:  
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"  

  orders:
    build: 
      context: .
      dockerfile: Orders/Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
      ConnectionStrings__Db: Server=shop-db;Port=5432;Database=Orders;User Id=${DB_USER};Password=${DB_PASSWORD}
      ConnectionStrings__BasketAndWishlist: http://basket-and-wishlist:8080/
      ConnectionStrings__Catalog: http://catalog:8080/
      KeycloakServiceConfig__AuthServerUrl: http://keycloak:8080/
    depends_on:
      - shop-db
    ports:
      - "8081:8080"

  catalog:
    build: 
      context: .
      dockerfile: Catalog/Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
      ConnectionStrings__Db: Server=shop-db;Port=5432;Database=Catalog;User Id=${DB_USER};Password=${DB_PASSWORD}
      KeycloakServiceConfig__AuthServerUrl: http://keycloak:8080/
    depends_on:
      - shop-db
    ports:
      - "8082:8080"

  basket-and-wishlist:
    build: 
      context: .
      dockerfile: BasketAndWishlist/Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
      ConnectionStrings__Db: Server=shop-db;Port=5432;Database=BasketAndWishlist;User Id=${DB_USER};Password=${DB_PASSWORD}
      ConnectionStrings__Catalog: http://catalog:8080/
      KeycloakServiceConfig__AuthServerUrl: http://keycloak:8080/
    depends_on:
      - shop-db
    ports:
      - "8083:8080"

  inventory:
    build:
      context: ./inventory  
      dockerfile: Dockerfile  
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - inventory-db
    ports:
      - "8084:5000" 