---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-db
  template:
    metadata:
      labels:
        app: shop-db
    spec:
      containers:
        - name: shop-db
          image: postgres:16.3
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PASSWORD
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: shop-db
  namespace: default
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: shop-db
